global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend-lab-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'backend-lab-api-direct'
    static_configs:
      - targets: ['api:8080']
